version: '3.8'
services:
  db:
    image: postgres:15
    container_name: gin-vue-admin-db
    environment:
      POSTGRES_USER: gva
      POSTGRES_PASSWORD: gva1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: gin-vue-admin-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local 